spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibirnate:
        jdbc:
          batch_size: ${batch.size}
        generate_statistics: true
    show-sql: true


batch.size: 1000

